
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andy Shaffer
 */
public class LoginFrame extends javax.swing.JFrame {
    databaseInterface apollo = new databaseInterface();
    Statement statement = null;
    
    /**
     * Creates new form MainFrame
     */
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        LoginPanel.setVisible(true);
        SSNPanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SSNPanel = new javax.swing.JPanel();
        SSNTitle = new javax.swing.JLabel();
        SSNLabel = new javax.swing.JLabel();
        SSN = new javax.swing.JTextField();
        SSNOK = new javax.swing.JButton();
        SSNCancel = new javax.swing.JButton();
        LoginPanel = new javax.swing.JPanel();
        LoginTitle = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        PassLabel = new javax.swing.JLabel();
        LoginOK = new javax.swing.JButton();
        LoginCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR Anywhere V0.12");
        setPreferredSize(new java.awt.Dimension(300, 220));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        SSNPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SSNPanel.setPreferredSize(null);

        SSNTitle.setText("Enter your SSN");

        SSNLabel.setText("SSN");

        SSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNActionPerformed(evt);
            }
        });

        SSNOK.setText("OK");
        SSNOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNOKActionPerformed(evt);
            }
        });

        SSNCancel.setText("Cancel");
        SSNCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SSNPanelLayout = new javax.swing.GroupLayout(SSNPanel);
        SSNPanel.setLayout(SSNPanelLayout);
        SSNPanelLayout.setHorizontalGroup(
            SSNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SSNPanelLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(SSNLabel)
                .addGap(18, 18, 18)
                .addComponent(SSN, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(SSNPanelLayout.createSequentialGroup()
                .addGroup(SSNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SSNPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(SSNOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SSNCancel))
                    .addGroup(SSNPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(SSNTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SSNPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SSNCancel, SSNOK});

        SSNPanelLayout.setVerticalGroup(
            SSNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SSNPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SSNTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(SSNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(SSNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSNOK)
                    .addComponent(SSNCancel))
                .addGap(22, 22, 22))
        );

        SSNPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SSNCancel, SSNOK});

        getContentPane().add(SSNPanel, "card2");

        LoginPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginPanel.setPreferredSize(null);

        LoginTitle.setText("Login to Apollo DB");

        UserLabel.setText("Username:");

        PassLabel.setText("Password:");

        LoginOK.setText("OK");
        LoginOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginOKActionPerformed(evt);
            }
        });

        LoginCancel.setText("Cancel");
        LoginCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(LoginOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LoginCancel))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(LoginTitle))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PassLabel)
                            .addComponent(UserLabel))
                        .addGap(18, 18, 18)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        LoginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LoginCancel, LoginOK});

        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassLabel)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginOK)
                    .addComponent(LoginCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(LoginPanel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginOKActionPerformed
        try {
            // TODO add your handling code here:
            String user=Username.getText();
            String pwd= new String (Password.getPassword());
            statement = apollo.establishConnection(user, pwd);
            LoginPanel.setVisible(false);
            SSNPanel.setVisible(true);
            JOptionPane.showMessageDialog(this,"Connected to Apollo Database", "Connection Established", JOptionPane.PLAIN_MESSAGE);

      
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_LoginOKActionPerformed

    private void LoginCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginCancelActionPerformed
        // TODO add your handling code here:
        apollo.dropConnection();
        System.exit(0);
    }//GEN-LAST:event_LoginCancelActionPerformed

    private void SSNOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNOKActionPerformed
        // TODO add your handling code here:
        String ssn=SSN.getText();
        int count = 0;
        try {
            ResultSet results = statement.executeQuery("select count(unique superssn) from employee where superssn =" + ssn);
            while (results.next())
              count = results.getInt(1);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (count == 1) {
            SSNPanel.setVisible(false);
            System.out.println("Manager Authenticated: " + ssn);
            new MainFrame(apollo, statement).setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Only managers may login to this system. ", "Invalid Authorization Attempt",
            JOptionPane.ERROR_MESSAGE);
            System.out.println("Unauthorized Access Attempt by SSN: " + ssn);
        }
    }//GEN-LAST:event_SSNOKActionPerformed

    private void SSNCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNCancelActionPerformed
        // TODO add your handling code here:
        apollo.dropConnection();
        System.exit(0);
    }//GEN-LAST:event_SSNCancelActionPerformed

    private void SSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSNActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginCancel;
    private javax.swing.JButton LoginOK;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField SSN;
    private javax.swing.JButton SSNCancel;
    private javax.swing.JLabel SSNLabel;
    private javax.swing.JButton SSNOK;
    private javax.swing.JPanel SSNPanel;
    private javax.swing.JLabel SSNTitle;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField Username;
    // End of variables declaration//GEN-END:variables
}
